version: '3.7'
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - app/.env
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  db-data:
